version: '3'
services:
  
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: ms-sql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      # user: sa
      - SA_PASSWORD=@Qwert123456789
      - MSSQL_PID=Developer
        
  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"